######################################################################
# Automatically generated by qmake (2.01a) Szo szept. 27 11:05:12 2014
######################################################################

TEMPLATE = app
TARGET = merger
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += merger.cpp
